### ISSUE TITLE
New task - Text box tests

### ISSUE THREAD

**Issue by hajdum** [Pongoo88/Robot-Testing#4]
In this task we will test Text box options in https://demoqa.com/text-box
We should create test cases that: 
1. fill up forms
2. fill up and delete forms
3. fields should also have different structures.. E.G. email should accept only email

**Comment by Pongoo88** [comment]
Done. Source files pushed to branch "4".

**Comment by hajdum** [comment]
@Pongoo88 Please create pull request against Main branch

**Comment by Pongoo88** [comment]
Merged to Main branch.

**Comment by hajdum** [comment]
I wanted you to only create pull request, not merge it :D but its okay.. i will check the changes
