### ISSUE TITLE
Test cases for Register user

### ISSUE THREAD

**Issue by hajdum** [Pongoo88/Robot-Testing#7]
Write test cases (not robot framework one.. but written as words) for user registration -> https://demoqa.com/register
Please cover happy case (the one that creates user)
Cover also different negative case scenarios ( for example dont type password)

**Comment by Pongoo88** [comment]
Done: 
[https://docs.google.com/spreadsheets/d/1AE93leQc-jx9B0_w99u2FY9R41puo86I/edit?usp=sharing&ouid=100036442691844442703&rtpof=true&sd=true](url)

**Comment by hajdum** [comment]
In general, it is good practise to name test cases as "Check banner in register user" and not as Banner. Reason behind this is that you can have several test cases checking something around Banner.

Current Test cases cover only visual checks, please add more test cases that cover filling up/deleting  the fields and dont forget to test Register and Back to login buttons :)  

Good job so far!

**Comment by hajdum** [comment]
Iv seen the second page of google sheet. Looks good!
